-- Adds file storage for documents (SOP, proposal, etc). Paste into Supabase
-- SQL Editor and run once.

alter table documents add column file_path text;

-- Private bucket: files are only reachable via short-lived signed URLs
-- generated by the app, not by a public link.
insert into storage.buckets (id, name, public)
values ('documents', 'documents', false)
on conflict (id) do nothing;

-- Same no-auth stance as the rest of the schema (see 0001_init.sql) — anon
-- key gets full access for now. Tighten this to `auth.role() = 'authenticated'`
-- if/when Supabase Auth is added.
create policy "anon full access to documents bucket"
on storage.objects for all
using (bucket_id = 'documents')
with check (bucket_id = 'documents');
